import { logger } from '@/lib/utils/logger';

export interface TurnstileValidationResult {
  success: boolean;
  error?: string;
  hostname?: string;
  action?: string;
  challengeTs?: string;
}

interface CloudflareSiteverifyResponse {
  success: boolean;
  'error-codes'?: string[];
  challenge_ts?: string;
  hostname?: string;
  action?: string;
  cdata?: string;
}

const SITEVERIFY_URL = 'https://challenges.cloudflare.com/turnstile/v0/siteverify';
const TIMEOUT_MS = 10_000;

// Cloudflare standard test secrets
const CLOUDFLARE_TEST_SECRETS = {
  ALWAYS_PASS: '1x0000000000000000000000000000000AA',
  ALWAYS_BLOCK: '2x0000000000000000000000000000000AB',
  INTERACTIVE: '3x0000000000000000000000000000000FF',
} as const;

/**
 * Validates a Cloudflare Turnstile token server-side.
 *
 * @param token The token (cf-turnstile-response) generated by the client widget
 * @param clientIp Optional client IP address
 * @param expectedAction Optional action name to match (e.g. 'verify', 'submit')
 */
export async function validateTurnstileToken(
  token: string | null | undefined,
  clientIp?: string,
  expectedAction?: string
): Promise<TurnstileValidationResult> {
  const secret = process.env.TURNSTILE_SECRET_KEY || process.env.TURNSTILE_SECRET;

  // In development or test environments without a configured secret, allow requests to proceed
  if (!secret) {
    if (process.env.NODE_ENV !== 'production') {
      logger.warn('Turnstile secret key not configured; bypassing verification in non-production mode', {
        service: 'Turnstile',
      });
      return { success: true };
    }

    logger.error('Turnstile secret key is missing in production environment', {
      service: 'Turnstile',
    });
    return {
      success: false,
      error: 'Configurația de securitate este incompletă.',
    };
  }

  // Token is required if Turnstile secret is configured
  if (!token || typeof token !== 'string' || token.trim().length === 0) {
    return {
      success: false,
      error: 'Verificarea de securitate (CAPTCHA) este obligatorie.',
    };
  }

  // Handle local mock / test secret shortcut
  if (secret === CLOUDFLARE_TEST_SECRETS.ALWAYS_BLOCK) {
    return {
      success: false,
      error: 'Verificarea de securitate a eșuat (test block).',
    };
  }

  try {
    const formData = new URLSearchParams();
    formData.append('secret', secret);
    formData.append('response', token.trim());
    if (clientIp) {
      formData.append('remoteip', clientIp);
    }

    const response = await fetch(SITEVERIFY_URL, {
      method: 'POST',
      body: formData,
      headers: {
        'Content-Type': 'application/x-www-form-urlencoded',
      },
      signal: AbortSignal.timeout(TIMEOUT_MS),
    });

    if (!response.ok) {
      logger.error('Turnstile siteverify HTTP error', {
        service: 'Turnstile',
        status: response.status,
      });
      return {
        success: false,
        error: 'Nu s-a putut valida verificarea de securitate.',
      };
    }

    const data = (await response.json()) as CloudflareSiteverifyResponse;

    if (!data.success) {
      logger.warn('Turnstile verification failed', {
        service: 'Turnstile',
        errorCodes: data['error-codes'],
      });
      return {
        success: false,
        error: 'Verificarea de securitate a eșuat. Te rugăm să reîncerci.',
      };
    }

    if (expectedAction && data.action && data.action !== expectedAction) {
      logger.warn('Turnstile action mismatch', {
        service: 'Turnstile',
        expected: expectedAction,
        received: data.action,
      });
      return {
        success: false,
        error: 'Acțiune de securitate nevalidă.',
      };
    }

    return {
      success: true,
      hostname: data.hostname,
      action: data.action,
      challengeTs: data.challenge_ts,
    };
  } catch (error) {
    logger.error('Unexpected error validating Turnstile token', {
      service: 'Turnstile',
      error: error instanceof Error ? error.message : String(error),
    });

    return {
      success: false,
      error: 'A apărut o eroare la verificarea de securitate. Te rugăm să reîncerci.',
    };
  }
}
