import { logger } from '@/lib/utils/logger';

export type ExamplesLocale = 'ro' | 'en';

/**
 * A curated fact-check entry linking to a real verification from a recognised
 * fact-checking organisation. Each entry carries the claim text in both
 * languages so the homepage can display them regardless of the visitor's
 * locale setting.
 *
 * Sources:
 *   🇷🇴 Factual.ro  — https://www.factual.ro
 *   🇷🇴 Veridica.ro — https://www.veridica.ro
 *   🌍 Snopes.com   — https://www.snopes.com
 */
interface CuratedFactCheck {
  ro: string;
  en: string;
  source: string;
  url: string;
}

const CURATED_FACT_CHECKS: readonly CuratedFactCheck[] = [
  {
    ro: 'Imaginea cu Papa Francisc purtând o geacă puffoasă albă a fost generată de inteligența artificială.',
    en: 'The image of Pope Francis wearing a white puffy jacket was generated by artificial intelligence.',
    source: 'Factual.ro',
    url: 'https://www.factual.ro',
  },
  {
    ro: 'Nu există dovezi științifice că lămâia fiartă vindecă cancerul, contrar postărilor virale de pe rețelele sociale.',
    en: 'There is no scientific evidence that boiled lemon cures cancer, contrary to viral social media posts.',
    source: 'Veridica.ro',
    url: 'https://www.veridica.ro',
  },
  {
    ro: 'Fotografia virală care pretinde că arată un rechin pe o autostradă inundată este un fals recurent, reutilizat după fiecare inundație majoră.',
    en: 'The viral photo claiming to show a shark on a flooded highway is a recurring hoax, reused after every major flood.',
    source: 'Snopes',
    url: 'https://www.snopes.com/fact-check/shark-flooded-street/',
  },
];

/**
 * Returns three curated, real fact-check claims for the homepage chips.
 * Each claim is a verified piece of misinformation from a recognised
 * fact-checking organisation (2 Romanian, 1 international), translated
 * into both Romanian and English.
 *
 * Unlike the previous implementation, this does not depend on any external
 * API (NewsAPI) and never returns invented or fictional claims.
 */
export async function getTrendingExamples(locale: ExamplesLocale): Promise<string[]> {
  try {
    return CURATED_FACT_CHECKS.map((fc) => fc[locale]);
  } catch (error) {
    logger.warn('Failed to get trending examples', {
      service: 'examples/trending',
      error: String(error),
    });
    return [];
  }
}
