import type {
  VerificationReport,
  CombinedSource,
  ReportBuilderParams,
} from '@/types/verification';
import { scoreToVerdict, scoreToConfidence } from './scoring';

/**
 * Extracts a 1-2 sentence executive summary from the full AI analysis.
 * Looks for the **Rezumat** / **Summary** section.
 */
export function extractExecutiveSummary(aiAnalysis: string): string {
  // Try to find bolded summary section
  const rezumatMatch = aiAnalysis.match(
    /\*\*Rezumat\*\*[\s\S]*?(?:\n+)([^\*]+?)(?:\n\n|\*\*|$)/
  );
  if (rezumatMatch?.[1]) return rezumatMatch[1].trim();

  const summaryMatch = aiAnalysis.match(
    /\*\*Summary\*\*[\s\S]*?(?:\n+)([^\*]+?)(?:\n\n|\*\*|$)/
  );
  if (summaryMatch?.[1]) return summaryMatch[1].trim();

  // Fallback: first 2 sentences
  const sentences = aiAnalysis
    .replace(/\*\*/g, '')
    .split(/(?<=[.!?])\s+/)
    .filter(s => s.trim().length > 10);

  return sentences.slice(0, 2).join(' ').trim();
}

/**
 * Combines sources from all layers into a unified, deduplicated, sorted list.
 */
function buildCombinedSources(params: ReportBuilderParams): CombinedSource[] {
  const { layer1, layer2, layer3, layer4 } = params;
  const sources: CombinedSource[] = [];

  // Layer 1: Fact-check sources
  for (const r of layer1.results) {
    if (!r.reviewUrl) continue;
    sources.push({
      title: `Fact-check: ${r.claimReviewed.slice(0, 80)}${r.claimReviewed.length > 80 ? '...' : ''}`,
      url: r.reviewUrl,
      publisher: r.publisher,
      publishedAt: r.reviewDate,
      sourceType: 'fact_check',
      relevance: r.relevanceScore,
      supports: r.ratingValue > 0.6 ? true : r.ratingValue < 0.4 ? false : null,
    });
  }

  // Layer 2: News articles
  for (const a of layer2.results) {
    if (!a.articleUrl) continue;
    sources.push({
      title: a.title,
      url: a.articleUrl,
      publisher: a.source,
      publishedAt: a.publishedAt,
      sourceType: 'news',
      relevance: a.credibilityScore,
      supports:
        a.sentiment === 'confirms' ? true
        : a.sentiment === 'contradicts' ? false
        : null,
    });
  }

  // Layer 3: Official sources
  for (const o of layer3.results) {
    if (!o.documentUrl) continue;
    sources.push({
      title: o.title,
      url: o.documentUrl,
      publisher: o.organization,
      publishedAt: o.publishedAt,
      sourceType: 'official',
      relevance: 0.9, // Official sources are always highly relevant
      supports:
        o.supportsOrDenies === 'supports' ? true
        : o.supportsOrDenies === 'denies' ? false
        : null,
    });
  }

  // Layer 4: Social media
  for (const p of layer4.results) {
    if (!p.postUrl) continue;
    sources.push({
      title: `${p.author}: "${p.content.slice(0, 60)}${p.content.length > 60 ? '...' : ''}"`,
      url: p.postUrl,
      publisher: p.platform,
      publishedAt: p.postDate,
      sourceType: 'social',
      relevance: p.isOriginalSource ? 0.8 : 0.4,
      supports: null, // Social media posts are informational, not verdicts
    });
  }

  // Deduplicate by URL
  const seen = new Set<string>();
  const unique = sources.filter(s => {
    if (!s.url || seen.has(s.url)) return false;
    seen.add(s.url);
    return true;
  });

  // Sort: official > fact_check > news > social, then by relevance
  const typeOrder = { official: 0, fact_check: 1, news: 2, social: 3 };
  unique.sort((a, b) => {
    const typeDiff = typeOrder[a.sourceType] - typeOrder[b.sourceType];
    if (typeDiff !== 0) return typeDiff;
    return b.relevance - a.relevance;
  });

  return unique.slice(0, 15);
}

/**
 * Builds the final VerificationReport from all layer results and AI analysis.
 */
export function buildReport(params: ReportBuilderParams): VerificationReport {
  const {
    input,
    layer1,
    layer2,
    layer3,
    layer4,
    scoreBreakdown,
    aiAnalysis,
    processingTime,
  } = params;

  const verdict = scoreToVerdict(scoreBreakdown.finalScore);
  const confidenceLevel = scoreToConfidence(scoreBreakdown.availableLayers);

  const disclaimer =
    input.language === 'ro'
      ? 'Acest raport este generat automat de un sistem AI și nu reprezintă o decizie editorială finală. Scorul de veridicitate este o estimare bazată pe sursele disponibile la momentul verificării. Consultați sursele citate pentru context complet. Aplicația nu preia responsabilitate pentru conținutul surselor externe.'
      : 'This report is automatically generated by an AI system and does not represent a final editorial decision. The veracity score is an estimate based on sources available at the time of verification. Consult the cited sources for full context. The application takes no responsibility for third-party source content.';

  const sources = buildCombinedSources(params);
  const executiveSummary = extractExecutiveSummary(aiAnalysis);

  return {
    id: crypto.randomUUID(),
    inputText: input.text,
    inputType: input.inputType,
    language: input.language,
    verdict,
    score: scoreBreakdown.finalScore,
    confidenceLevel,
    scoreBreakdown,
    executiveSummary,
    layer1,
    layer2,
    layer3,
    layer4,
    aiAnalysis,
    sources,
    disclaimer,
    processingTime,
    createdAt: new Date().toISOString(),
    isPublic: input.isPublic,
    userId: input.userId,
    fromCache: false,
  };
}
